[package]
name = "testbot"
version = "0.1.0"
authors = ["Andrew Halberstadt <ahal@pm.me>"]
edition = "2018"

[dependencies]
matrix-bot = { path = ".." }
matrix-sdk = {"version" = "*", features = ["encryption", "sqlite_cryptostore"]}
uuid = {"version" = "^0.8.2", features = ["v4"]}
