[package]
name = "botzilla"
version = "0.1.0"
authors = ["Andrew Halberstadt <ahal@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix_bot_api = "0.5.2"

[[bin]]
name = "botzilla"
path = "src/bin.rs"
