[package]
name = "botzilla"
version = "0.1.0"
authors = ["Andrew Halberstadt <ahal@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "^3.0.1"
matrix-sdk = "0.2.0"
tokio = {"version"= "^0.2.0", features=["rt-threaded", "macros"]}
tracing-subscriber = "^0.2.17"
url = "^2.2.1"

[[bin]]
name = "botzilla"
path = "src/bot.rs"
