[package]
name = "matrix-bot"
version = "0.1.0"
authors = ["Andrew Halberstadt <ahal@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "^3.0.1"
matrix-sdk = {"version" = "0.2.0", features = ["encryption", "sqlite_cryptostore"]}
tokio = {"version" = "^0.2.0", features = ["rt-threaded", "macros"]}
tracing-subscriber = "^0.2.17"
url = "^2.2.1"
uuid = {"version" = "^0.8.2", features = ["v4"]}

[[bin]]
name = "testbot"
path = "src/bot.rs"
